exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock"]
auto: true
pygments: true

title : Rails Girls Guide -Japanese- // test
tagline: Site Tagline
author :
  name : Iku Nakamura
  email : iku.nakamura@gmail.com
  github : somali
  twitter : somali
  feedburner : feedname

production_url : somali.github.com

destination: ./_site
lsi:         false
server_port: 4000
markdown: rdiscount
permalink:   pretty
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

comments :
  provider : disqus
  disqus :
    short_name : somali
